name: build
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.0.2']
        cabal: ['3.6']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Haskell GHC ${{ matrix.ghc }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: |
          cabal test 